name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flutter_job:

    # Options: macos-latest, windows-latest, ubuntu-latest
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      # TODO: Move to git pre-commit hook
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyse project source
        run: flutter analyze --fatal-warnings

      - name: Run tests
        run: flutter test



