name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flutter_job:

    # Options: macos-latest, windows-latest, ubuntu-latest
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      # TODO: Move to git pre-commit hook
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyse project source
        run: flutter analyze --fatal-warnings

      - name: Run tests
        run: flutter test

      - name: Build apk
        run: flutter build apk

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Upload apk to Firebase distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
           appId: ${{ vars.FIREBASE_APP_ID_ANDROID }}
           serviceCredentialsFileContent: ${{ secrets.FIREBASE_TOKEN }}
           groups: all_testers
           file: build/app/outputs/flutter-apk/app-release.apk

      # TODO:
        # Sign Apk and push to Play Store
        # Sort iOS signing and generate IPA
      
        # [1] https://prasadsunny1.medium.com/minimal-ci-cd-setup-with-flutter-and-github-actions-part-3-10eb1823dd96
